TASKS = [
    {
        "id": "easy",
        "description": "Obvious spam vs normal email",
        "emails": [
            {"text": "Win a free iPhone now!", "label": "spam"},
            {"text": "Get rich quick scheme!!!", "label": "spam"},
            {"text": "Meeting at 3pm tomorrow", "label": "not_spam"},
            {"text": "Lunch plans?", "label": "not_spam"},
            {"text": "Claim your free reward now", "label": "spam"},
            {"text": "Project update attached", "label": "not_spam"},
            {"text": "Limited offer just for you", "label": "spam"},
            {"text": "Call me when you're free", "label": "not_spam"},
            {"text": "You've won a lottery!", "label": "spam"},
            {"text": "Team meeting rescheduled", "label": "not_spam"},
        ],
    },
    {
        "id": "medium",
        "description": "Promotional vs legitimate service emails",
        "emails": [
            {"text": "Limited time discount just for you", "label": "spam"},
            {"text": "Your order has been shipped", "label": "not_spam"},
            {"text": "Exclusive deal on electronics", "label": "spam"},
            {"text": "Your invoice is attached", "label": "not_spam"},
            {"text": "Flash sale ends tonight", "label": "spam"},
            {"text": "Password reset confirmation", "label": "not_spam"},
            {"text": "Buy now and save big", "label": "spam"},
            {"text": "Subscription renewed successfully", "label": "not_spam"},
            {"text": "Special promotion for valued customers", "label": "spam"},
            {"text": "Delivery confirmation", "label": "not_spam"},
            {"text": "Huge discounts available now", "label": "spam"},
            {"text": "Your support ticket has been resolved", "label": "not_spam"},
        ],
    },
    {
        "id": "hard",
        "description": "Detect subtle phishing attempts",
        "emails": [
            {"text": "Update your account to avoid suspension", "label": "spam"},
            {"text": "Quarterly performance report attached", "label": "not_spam"},
            {"text": "Verify your login credentials immediately", "label": "spam"},
            {"text": "Team performance review meeting notes", "label": "not_spam"},
            {"text": "Unusual activity detected, confirm identity", "label": "spam"},
            {"text": "Monthly financial summary attached", "label": "not_spam"},
            {"text": "Click here to secure your account", "label": "spam"},
            {"text": "Project documentation update", "label": "not_spam"},
            {"text": "We noticed suspicious login attempts", "label": "spam"},
            {"text": "Client feedback report", "label": "not_spam"},
            {"text": "Immediate password reset required", "label": "spam"},
            {"text": "Weekly team sync notes", "label": "not_spam"},
            {"text": "Confirm your account details urgently", "label": "spam"},
            {"text": "Internal audit report", "label": "not_spam"},
        ],
    },
]